#!/usr/bin/env python
#Fix and uncomment those 2 lines if your moin command doesn't find the MoinMoin package:
import os
import sys
cur_dir = os.path.dirname(os.path.realpath(__file__))
path = os.path.join(cur_dir, "config")
sys.path.insert(0, cur_dir)
from MoinMoin.script.moin import run
run()
